services:
  - type: web
    name: griddatahub
    runtime: docker
    repo: https://github.com/imp-joshi/griddatahub
    branch: main
    dockerfilePath: ./dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11
      - key: LOG_LEVEL
        value: info
    buildCommand: echo "Building Docker image..."
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
