services:
  - type: web
    name: power-grid-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11